name: ✍️ Issue Quality Enhancer

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  enhance:
    uses: __OWNER__/agentic-repo/.github/workflows/issue-quality-enhancer.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      issue_author: ${{ github.event.issue.user.login }}
    secrets: inherit
