name: 🏷️✨ Label Beautifier

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode (only show changes, do not apply them)'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

permissions: {}

jobs:
  beautify:
    uses: __OWNER__/agentic-repo/.github/workflows/label-beautifier.yml@main
    with:
      dry_run: ${{ inputs.dry_run }}
    secrets: inherit
