name: 🔍 PR Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]

# Cancel in-progress runs for the same PR to avoid wasting Actions minutes
# when multiple commits are pushed in quick succession.
concurrency:
  group: ${{ github.repository }}-pr-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  review:
    uses: __OWNER__/agentic-repo/.github/workflows/pr-code-reviewer.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_author: ${{ github.event.pull_request.user.login }}
      base_ref: ${{ github.event.pull_request.base.ref }}
      head_ref: ${{ github.event.pull_request.head.ref }}
    secrets: inherit
