name: 💡 Copilot Suggester (Discussion Mode)

on:
  workflow_dispatch:
    inputs:
      suggestion_type:
        description: 'Type of suggestions to look for'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - security
          - performance
          - refactoring
          - testing
          - documentation
          - architecture
          - configuration
          - bugs
          - maintainability
          - ux-design
          - readme
      analyze_ui:
        description: 'Attempt to build, run, and analyze the application UI via Playwright'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  suggest:
    uses: __OWNER__/agentic-repo/.github/workflows/the-suggester-discussion-mode.yml@main
    with:
      suggestion_type: ${{ inputs.suggestion_type }}
      analyze_ui: ${{ inputs.analyze_ui }}
    secrets: inherit
